" my vim profile
" update 2014-07-29 09:12:00
" UNCOMPLETE

set nocompatible

set history=1000
set undolevels=1000
set undofile
set undodir=$HOME/.vim/undos

" syntax and encoding
syntax on
syntax enable
set encoding=utf-8
set fileencodings=utf-8,gb2312,ucs-bom,euc-cn,euc-tw,gb18030,gbk,cp936,latin1,big5

"set smartindent
"set cindent
"set autoindent

" auto filetype and indent
filetype plugin indent on

" tab
set shiftwidth=4
set tabstop=4
" set softtabstop=4
set expandtab

set backspace=indent,eol,start

set showmatch
set number " 显示行号
set cursorline " 突出显示当前行
set ruler " 打开状态栏标尺

set nobackup " 覆盖文件时不备份
set backupcopy=yes " 设置备份时的行为为覆盖
set ignorecase smartcase " 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set incsearch " 输入搜索内容时就显示搜索结果
set hlsearch " 搜索时高亮显示被找到的文本
set noerrorbells " 关闭错误信息响铃
set novisualbell " 关闭使用可视响铃代替呼叫
set t_vb= " 置空错误铃声的终端代码
set hidden " 允许在有未保存的修改时切换缓冲区，此时的修改由 vim 负责保存
"set magic " 设置魔术
"set nowrapscan " 禁止在搜索到文件两端时重新搜索

" set mouse=a

" imap
imap jk <esc>:w<CR>
imap kj <esc>:w<CR>
imap jK <esc>:w<CR>
imap kJ <esc>:w<CR>
imap JK <esc>:w<CR>
imap KJ <esc>:w<CR>
imap Jk <esc>:w<CR>
imap Kj <esc>:w<CR>
imap zxj <c-r>=strftime("20%y-%m-%d %H:%M:%S")<cr>

" Using templates with .vim/templates
let g:template_load = 1
let g:template_tags_replacing = 1
let g:T_AUTHOR = "illuz"
let g:T_AUTHOR_EMAIL = "iilluzen[at]gmail.com"
let g:T_AUTHOR_WEBSITE = "http://blog.csdn.net/hcbbt"
let g:T_DATE_FORMAT = "%c"

" Stop using the h, j, k, l keys!
" Like http://vimcasts.org/blog/2013/02/habit-breaking-habit-making/ says
" noremap h <NOP>
" noremap j <NOP>
" noremap k <NOP>
" noremap l <NOP>

"gvim
"set guioptions-=T " 隐藏工具栏
"set guioptions-=m " 隐藏菜单栏



" Solarized stuff
let g:solarized_termtrans = 1
set background=dark
colorscheme solarized
